### ISSUE TITLE
Lock psql execution

### ISSUE THREAD

**Issue by benoittgt** [imomaliev/registers.vim#1]
Hello

When editing SQL in psql with `\e`. The plugin lock the execution of the query when we save. The query it's not executed.
```
"/private/var/folders/n4/62hl6hgj13l5j_2lbr0000gp/T/psql.edit.836.sql" 1L, 30C written
db_name=# \e
Error detected while processing /Users/bti/.vim/plugged/registers.vim/plugin/registers.vim:
line   28:
E216: No such group or event: CompleteDone * call registers#PasteRegister()
```

**Comment by imomaliev** [comment]
Hello,

I need more info how exactly you are running psql in vim?

**Comment by benoittgt** [comment]
You run `psql` then `\e` and if it's properly configured vim will open the last SQL command.

http://www.craigkerstiens.com/2013/02/21/more-out-of-psql/

**Comment by benoittgt** [comment]
Stale issue. Closing for now.
